version: "2"

services:
 glassfish:
   build: ./server
   #image: glassfish3:v4
   ports:
     - "8080:8080"
     - "4848:4848"
     - "222:22"
     - "9999-15000:9999-15000"
   #volumes:
   #  - /opt/dockerVol/glassfish/autodeploy:/usr/local/glassfish3/glassfish/domains/domain1/autodeploy

#apache:
#    #build : ./repo
#     image: trinitronx/python-simplehttpserver
#     ports: 
#      - '9091:8080'
#     volumes:
#      - '/home/ingsoluciones/builder-TesterComposeDocker/repo/installers:/var/www:ro' 



 nexus:
   #build: ./repoDepend
   image: sonatype/nexus
   ports:
     - "6091:8081"
   volumes:
     - /opt/dockerVol/nexusData:/sonatype-work

 jenkins:
    build: ./builder
    #image: 'jenk-mvn-git-nex:v1'
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    links:
      - nexus 
    ports:
      - "50000:50000"
      - "6090:8080"
    volumes:
      - /opt/dockerVol/jenkinsData/jobs:/var/jenkins_home/jobs
      - /opt/dockerVol/glassfish/Autodeploy:/opt/dockerVol/glassfish/deploy
