version: "2"
services:
 glassfish:
   build: ./server
   #image: glassfish3:v4
   ports:
     - "8080:8080"
     - "4848:4848"

#apache:
#    #build : ./repo
#     image: trinitronx/python-simplehttpserver
#     ports: 
#      - '9091:8080'
#     volumes:
#      - '/home/ingsoluciones/builder-TesterComposeDocker/repo/installers:/var/www:ro' 


 nexus:
   build :/repoDepend
   #image: sonatype/nexus
   volumes:
     - "nexus-data:/sonatype-work"
   ports:
     - "6091:8081"
  
   volumes:
     - /home/ingsoluciones/nexusData:/sonatype-work

 
 jenkins:
    build: ./builder
    #image: 'jenk-mvn-git-nex:v1'
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "6090:8080"
    volumes:
      - /home/ingsoluciones/jenkinsDockerVolume/jobs:/var/jenkins_home/jobs
